In [1]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("large_student_data.csv")
df.head()
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City,Semester,CGPA
495,1496,Aditya,19,ECE,86,97,Nashik,6,8.47
496,1497,Aditya,21,CSE,55,78,Thane,1,6.98
497,1498,Kavya,22,AI,80,87,Pune,3,8.77
498,1499,Vivaan,25,AI,71,97,Nagpur,2,5.49
499,1500,Kavya,21,IT,83,60,Nashik,8,6.37

In [6]:
df.describe()

,Student_ID,Age,Marks,Attendance_Percentage,Semester,CGPA
count,500.000000,500.00000,500.000000,500.00000,500.000000,500.000000
mean,1250.500000,21.45000,74.904000,80.03000,4.462000,7.552520
std,144.481833,2.24088,14.513858,11.99587,2.308075,1.449301
min,1001.000000,18.00000,50.000000,60.00000,1.000000,5.000000
25%,1125.750000,20.00000,62.000000,70.00000,2.750000,6.310000
50%,1250.500000,22.00000,75.000000,80.00000,4.000000,7.585000
75%,1375.250000,23.00000,87.000000,90.00000,7.000000,8.750000
max,1500.000000,25.00000,100.000000,100.00000,8.000000,10.000000

In [8]:
df.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                      int64
Attendance_Percentage      int64
City                      object
Semester                   int64
CGPA                     float64
dtype: object

In [9]:
df.isnull()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City,Semester,CGPA
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False

In [10]:
df[df.isnull()]

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City,Semester,CGPA
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [12]:
df.isnull().sum()

Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    0
Attendance_Percentage    0
City                     0
Semester                 0
CGPA                     0
dtype: int64

In [13]:
df.fillna(0)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City,Semester,CGPA
0,1001,Priya,22,Cyber Security,94,65,Palghar,1,5.19
1,1002,Manasi,23,CSE,67,60,Delhi,5,9.25
2,1003,Riya,22,ECE,62,86,Nagpur,7,8.30
3,1004,Vihaan,23,DS,92,82,Thane,4,6.53
4,1005,Vivaan,20,CSE,85,70,Palghar,6,5.92
...,...,...,...,...,...,...,...,...,...
495,1496,Aditya,19,ECE,86,97,Nashik,6,8.47
496,1497,Aditya,21,CSE,55,78,Thane,1,6.98
497,1498,Kavya,22,AI,80,87,Pune,3,8.77
498,1499,Vivaan,25,AI,71,97,Nagpur,2,5.49
499,1500,Kavya,21,IT,83,60,Nashik,8,6.37

In [14]:
df['Marks']=df["Marks"].fillna(df["Marks"].mean())

In [15]:
df.dtypes

Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                      int64
Attendance_Percentage      int64
City                      object
Semester                   int64
CGPA                     float64
dtype: object

In [22]:
df=df.rename(columns={'Age':'Agee'})
df.head()

,Student_ID,Name,Agee,Course,Marks,Attendance_Percentage,City,Semester,CGPA
0,1001,Priya,22,Cyber Security,94,65,Palghar,1,5.19
1,1002,Manasi,23,CSE,67,60,Delhi,5,9.25
2,1003,Riya,22,ECE,62,86,Nagpur,7,8.30
3,1004,Vihaan,23,DS,92,82,Thane,4,6.53
4,1005,Vivaan,20,CSE,85,70,Palghar,6,5.92

In [25]:
df["Attendance_Percentage"]=df["Attendance_Percentage"].astype(float)
df.head(5)

,Student_ID,Name,Agee,Course,Marks,Attendance_Percentage,City,Semester,CGPA
0,1001,Priya,22,Cyber Security,94,65.0,Palghar,1,5.19
1,1002,Manasi,23,CSE,67,60.0,Delhi,5,9.25
2,1003,Riya,22,ECE,62,86.0,Nagpur,7,8.30
3,1004,Vihaan,23,DS,92,82.0,Thane,4,6.53
4,1005,Vivaan,20,CSE,85,70.0,Palghar,6,5.92

In [29]:
df["Semester"]=df["Semester"].apply(lambda x:x*2)
df.head(4)

,Student_ID,Name,Agee,Course,Marks,Attendance_Percentage,City,Semester,CGPA
0,1001,Priya,22,Cyber Security,94,65.0,Palghar,2,5.19
1,1002,Manasi,23,CSE,67,60.0,Delhi,781250,9.25
2,1003,Riya,22,ECE,62,86.0,Nagpur,11529602,8.30
3,1004,Vihaan,23,DS,92,82.0,Thane,131072,6.53

In [33]:
grouped_mean=df.groupby("Course")["Marks"].mean()
print(grouped_mean)

Course
AI                76.432432
CSE               78.047619
Cyber Security    72.894737
DS                73.800000
ECE               73.044776
IT                76.962500
Mechanical        73.213333
Name: Marks, dtype: float64

In [34]:
grouped_sum=df.groupby(["Course","City"])["Marks"].sum()
print(grouped_sum)

Course          City
AI              Delhi       465
                Mumbai      759
                Nagpur      839
                Nashik     1127
                Palghar     782
                Pune        917
                Thane       767
CSE             Delhi       725
                Mumbai      217
                Nagpur      630
                Nashik      949
                Palghar     957
                Pune        676
                Thane       763
Cyber Security  Delhi       811
                Mumbai      663
                Nagpur     1222
                Nashik      549
                Palghar     526
                Pune        970
                Thane       799
DS              Delhi       641
                Mumbai      308
                Nagpur      552
                Nashik     1026
                Palghar     625
                Pune        684
                Thane       961
ECE             Delhi       621
                Mumbai      855
                Nagpur     1090
                Nashik      486
                Palghar     468
                Pune        759
                Thane       615
IT              Delhi       525
                Mumbai     1097
                Nagpur     1223
                Nashik      864
                Palghar     612
                Pune       1136
                Thane       700
Mechanical      Delhi       756
                Mumbai     1265
                Nagpur      725
                Nashik      732
                Palghar     583
                Pune        796
                Thane       634
Name: Marks, dtype: int64

In [38]:
grouped_aggregate=df.groupby("City")["Marks"].agg(["mean","sum","count"])
print(grouped_aggregate)

              mean   sum  count
City
Delhi    72.126984  4544     63
Mumbai   74.840580  5164     69
Nagpur   75.674699  6281     83
Nashik   72.569620  5733     79
Palghar  75.883333  4553     60
Pune     76.128205  5938     78
Thane    77.044118  5239     68

In [ ]:
df1=pd.DataFrame({"keys":['a','b','c'],"value1":[1,2,3]})
df2=pd.DataFrame({"keys":['a','b','d'],"value2":[4,5,6]})

In [40]:
df1

  keys  values
0    a       1
1    b       2
2    c       3

In [41]:
df2

  keys  values
0    a       4
1    b       5
2    d       6

In [42]:
#merge dataframe on key columns
pd.merge(df1,df2, on="keys",how="inner")

  keys  values_x  values_y
0    a         1         4
1    b         2         5

In [43]:
pd.merge(df1,df2, on="keys",how="outer")

  keys  values_x  values_y
0    a       1.0       4.0
1    b       2.0       5.0
2    c       3.0       NaN
3    d       NaN       6.0

In [44]:
pd.merge(df1,df2, on="keys",how="left")

  keys  values_x  values_y
0    a         1       4.0
1    b         2       5.0
2    c         3       NaN

In [45]:
pd.merge(df1,df2, on="keys",how="right")

  keys  values_x  values_y
0    a       1.0         4
1    b       2.0         5
2    d       NaN         6