In [1]:
!pip install pandas

Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in d:\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
data=[1,2,3,4,5]
data_series=pd.Series(data)
print(data_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
data1={'a':1,'b':2,'c':3}
data_series1=pd.Series(data1)
print(data_series1)

a    1
b    2
c    3
dtype: int64

In [7]:
data2=[1,2,3,4]
index=['a','b','c','d']
print(pd.Series(data2,index=index))

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
## create dataframe from dictionary of lists
data4={
    "name":["manasi","gargee","renuka"],
    "age":[22,14,13],
    "city":["pune","mumbai","banglore"]
}
df=pd.DataFrame(data4)
print(df)
print(type(df))

     name  age      city
0  manasi   22      pune
1  gargee   14    mumbai
2  renuka   13  banglore
<class 'pandas.core.frame.DataFrame'>

In [11]:
import numpy as np
np.array(df)

array([['manasi', 22, 'pune'],
       ['gargee', 14, 'mumbai'],
       ['renuka', 13, 'banglore']], dtype=object)

In [15]:
## create dataframe from list of dcitionaries
data4=[
    {"name":"manasi","age":22,"city":"pune"},
    {"name":"gargee","age":14,"city":"mumbai"},
    {"name":"renuka","age":13,"city":"banglore"}
]
df=pd.DataFrame(data4)
print(df)
print(type(df))

     name  age      city
0  manasi   22      pune
1  gargee   14    mumbai
2  renuka   13  banglore
<class 'pandas.core.frame.DataFrame'>

In [4]:
import pandas as pd
df1=pd.read_csv("large_student_data.csv")
df1.head(5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City,Semester,CGPA
0,1001,Priya,22,Cyber Security,94,65,Palghar,1,5.19
1,1002,Manasi,23,CSE,67,60,Delhi,5,9.25
2,1003,Riya,22,ECE,62,86,Nagpur,7,8.30
3,1004,Vihaan,23,DS,92,82,Thane,4,6.53
4,1005,Vivaan,20,CSE,85,70,Palghar,6,5.92

In [5]:
df1.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City,Semester,CGPA
495,1496,Aditya,19,ECE,86,97,Nashik,6,8.47
496,1497,Aditya,21,CSE,55,78,Thane,1,6.98
497,1498,Kavya,22,AI,80,87,Pune,3,8.77
498,1499,Vivaan,25,AI,71,97,Nagpur,2,5.49
499,1500,Kavya,21,IT,83,60,Nashik,8,6.37

In [ ]:
df1.loc[0,"Name"] #row number and column name

'Priya'

In [24]:
df1.iloc[5][6] #row and column number

C:\Users\manas\AppData\Local\Temp\ipykernel_138088\3827336895.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df1.iloc[5][6] #row and column number

'Pune'

In [25]:
df1.at[1,"Name"]

'Manasi'

In [15]:
df1.iat[2,3]

'ECE'

In [23]:
df1.describe()

,Student_ID,Age,Marks,Attendance_Percentage,Semester,CGPA
count,500.000000,500.00000,500.000000,500.00000,500.000000,500.000000
mean,1250.500000,21.45000,74.904000,80.03000,4.462000,7.552520
std,144.481833,2.24088,14.513858,11.99587,2.308075,1.449301
min,1001.000000,18.00000,50.000000,60.00000,1.000000,5.000000
25%,1125.750000,20.00000,62.000000,70.00000,2.750000,6.310000
50%,1250.500000,22.00000,75.000000,80.00000,4.000000,7.585000
75%,1375.250000,23.00000,87.000000,90.00000,7.000000,8.750000
max,1500.000000,25.00000,100.000000,100.00000,8.000000,10.000000

In [26]:
df1.drop(0)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City,Semester,CGPA
1,1002,Manasi,23,CSE,67,60,Delhi,5,9.25
2,1003,Riya,22,ECE,62,86,Nagpur,7,8.30
3,1004,Vihaan,23,DS,92,82,Thane,4,6.53
4,1005,Vivaan,20,CSE,85,70,Palghar,6,5.92
5,1006,Aarav,22,Cyber Security,70,77,Pune,8,9.61
...,...,...,...,...,...,...,...,...,...
495,1496,Aditya,19,ECE,86,97,Nashik,6,8.47
496,1497,Aditya,21,CSE,55,78,Thane,1,6.98
497,1498,Kavya,22,AI,80,87,Pune,3,8.77
498,1499,Vivaan,25,AI,71,97,Nagpur,2,5.49
499,1500,Kavya,21,IT,83,60,Nashik,8,6.37